languageCode = "en"
languageName = "English"
weight = 1
title = "Sholim"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  # logo = "img/logo.png"
  description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"
  dateFormat = "2 January 2006"

[params.author]
  name = "Sholim"
  image = "img/cover.png"
  headline = "Security analyst | ctf player" 
  #links = [{link = "https://blog.pwnus.site"}]
  bio = "Security analyst"
   links = [
     { linkedin = "https://www.linkedin.com/in/kevin-kimaiyo-29531a205" },
     { github = "https://github.com/Kevinsholim06" },
     { x-twitter = "https://x.com/Shol1m" },
     { team = "https://teamphantomctf.com" }
   ]

[params.author.team]
  name = "Team Phantom"
  link = "https://teamphantomctf.com" # direct homepage link
